#############################################################################
# Makefile for building: QtBoardGames.app/Contents/MacOS/QtBoardGames
# Generated by qmake (3.1) (Qt 6.3.0)
# Project:  QtBoardGames.pro
# Template: app
# Command: /Users/octavian.cimpu/Qt/6.3.0/macos/bin/qmake -o QtBoardGames.xcodeproj/project.pbxproj QtBoardGames.pro -spec macx-xcode -qtconf /Users/octavian.cimpu/Qt/6.3.0/ios/bin/target_qt.conf
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/octavian.cimpu/Qt/6.3.0/macos/bin/qmake
QtBoardGames.xcodeproj/project.pbxproj: QtBoardGames.pro ../../Qt/6.3.0/ios/mkspecs/macx-ios-clang/qmake.conf ../../Qt/6.3.0/ios/mkspecs/features/spec_pre.prf \
		../../Qt/6.3.0/ios/mkspecs/qdevice.pri \
		../../Qt/6.3.0/ios/mkspecs/features/device_config.prf \
		../../Qt/6.3.0/ios/mkspecs/common/unix.conf \
		../../Qt/6.3.0/ios/mkspecs/common/mac.conf \
		../../Qt/6.3.0/ios/mkspecs/common/uikit.conf \
		../../Qt/6.3.0/ios/mkspecs/common/ios.conf \
		../../Qt/6.3.0/ios/mkspecs/common/sanitize.conf \
		../../Qt/6.3.0/ios/mkspecs/common/gcc-base.conf \
		../../Qt/6.3.0/ios/mkspecs/common/gcc-base-mac.conf \
		../../Qt/6.3.0/ios/mkspecs/common/clang.conf \
		../../Qt/6.3.0/ios/mkspecs/common/clang-mac.conf \
		../../Qt/6.3.0/ios/mkspecs/common/uikit/clang.conf \
		../../Qt/6.3.0/ios/mkspecs/common/uikit/qmake.conf \
		../../Qt/6.3.0/ios/mkspecs/qconfig.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_pcre2.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_freetype_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmllint_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webviewquick.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qcertonlybackend.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qscnetworkreachability.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsecuretransportbackend.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		../../Qt/6.3.0/ios/mkspecs/features/qt_functions.prf \
		../../Qt/6.3.0/ios/mkspecs/features/qt_config.prf \
		../../Qt/6.3.0/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../Qt/6.3.0/ios/mkspecs/macx-xcode/qmake.conf \
		../../Qt/6.3.0/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.3.0/ios/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/sdk.prf \
		../../Qt/6.3.0/ios/mkspecs/features/uikit/sdk.prf \
		../../Qt/6.3.0/ios/mkspecs/features/toolchain.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/toolchain.prf \
		../../Qt/6.3.0/ios/mkspecs/features/default_pre.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/default_pre.prf \
		../../Qt/6.3.0/ios/mkspecs/features/uikit/default_pre.prf \
		../../Qt/6.3.0/ios/mkspecs/features/resolve_config.prf \
		../../Qt/6.3.0/ios/mkspecs/features/uikit/resolve_config.prf \
		../../Qt/6.3.0/ios/mkspecs/features/default_post.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/default_post.prf \
		../../Qt/6.3.0/ios/mkspecs/features/uikit/default_post.prf \
		../../Qt/6.3.0/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/objective_c.prf \
		../../Qt/6.3.0/ios/mkspecs/features/entrypoint.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/mac.prf \
		../../Qt/6.3.0/ios/mkspecs/features/uikit/bitcode.prf \
		../../Qt/6.3.0/ios/mkspecs/features/warn_on.prf \
		../../Qt/6.3.0/ios/mkspecs/features/qt.prf \
		../../Qt/6.3.0/ios/mkspecs/features/resources_functions.prf \
		../../Qt/6.3.0/ios/mkspecs/features/resources.prf \
		../../Qt/6.3.0/ios/mkspecs/features/moc.prf \
		../../Qt/6.3.0/ios/mkspecs/features/unix/opengl.prf \
		../../Qt/6.3.0/ios/mkspecs/features/uic.prf \
		../../Qt/6.3.0/ios/mkspecs/features/unix/thread.prf \
		../../Qt/6.3.0/ios/mkspecs/features/qmake_use.prf \
		../../Qt/6.3.0/ios/mkspecs/features/file_copies.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/rez.prf \
		../../Qt/6.3.0/ios/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/6.3.0/ios/mkspecs/features/testcase_targets.prf \
		../../Qt/6.3.0/ios/mkspecs/features/uikit/testcase_targets.prf \
		../../Qt/6.3.0/ios/mkspecs/features/exceptions.prf \
		../../Qt/6.3.0/ios/mkspecs/features/yacc.prf \
		../../Qt/6.3.0/ios/mkspecs/features/lex.prf \
		QtBoardGames.pro \
		../../Qt/6.3.0/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard \
		qml.qrc \
		../../Qt/6.3.0/ios/plugins/platforms/libqios.prl \
		../../Qt/6.3.0/ios/plugins/iconengines/libqsvgicon.prl \
		../../Qt/6.3.0/ios/plugins/imageformats/libqgif.prl \
		../../Qt/6.3.0/ios/plugins/imageformats/libqico.prl \
		../../Qt/6.3.0/ios/plugins/imageformats/libqjpeg.prl \
		../../Qt/6.3.0/ios/plugins/imageformats/libqsvg.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_debugger.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_inspector.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_local.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_messages.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_native.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_preview.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_profiler.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_server.prl \
		../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_tcp.prl \
		../../Qt/6.3.0/ios/plugins/networkinformation/libqscnetworkreachability.prl \
		../../Qt/6.3.0/ios/plugins/tls/libqsecuretransportbackend.prl \
		../../Qt/6.3.0/ios/lib/libQt6Quick.prl \
		../../Qt/6.3.0/ios/lib/libQt6OpenGL.prl \
		../../Qt/6.3.0/ios/lib/libQt6Widgets.prl \
		../../Qt/6.3.0/ios/lib/libQt6Gui.prl \
		../../Qt/6.3.0/ios/lib/libQt6QmlModels.prl \
		../../Qt/6.3.0/ios/lib/libQt6Qml.prl \
		../../Qt/6.3.0/ios/lib/libQt6Network.prl \
		../../Qt/6.3.0/ios/lib/libQt6Core.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/libqtquick2plugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Particles/libparticlesplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQml/libqmlplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQml/Models/libmodelsplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQml/WorkerScript/libworkerscriptplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Window/libquickwindowplugin.prl \
		../../Qt/6.3.0/ios/qml/QtDigitalAdvertising/libDigitalAdvertising.prl \
		../../Qt/6.3.0/ios/qml/QtWebView/libqtwebviewquickplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/libqtquickcontrols2plugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/impl/libqtquickcontrols2implplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Basic/libqtquickcontrols2basicstyleplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Fusion/libqtquickcontrols2fusionstyleplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Material/libqtquickcontrols2materialstyleplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Imagine/libqtquickcontrols2imaginestyleplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Universal/libqtquickcontrols2universalstyleplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Templates/libqtquicktemplates2plugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Shapes/libqmlshapesplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Basic/impl/libqtquickcontrols2basicstyleimplplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Fusion/impl/libqtquickcontrols2fusionstyleimplplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Material/impl/libqtquickcontrols2materialstyleimplplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Imagine/impl/libqtquickcontrols2imaginestyleimplplugin.prl \
		../../Qt/6.3.0/ios/qml/QtQuick/Controls/Universal/impl/libqtquickcontrols2universalstyleimplplugin.prl \
		../../Qt/6.3.0/ios/qml/Qt/labs/platform/libqtlabsplatformplugin.prl \
		../../Qt/6.3.0/ios/qml/QtMultimedia/libquickmultimediaplugin.prl
	$(QMAKE) -o QtBoardGames.xcodeproj/project.pbxproj QtBoardGames.pro -spec macx-xcode -qtconf /Users/octavian.cimpu/Qt/6.3.0/ios/bin/target_qt.conf
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
../../Qt/6.3.0/ios/mkspecs/features/spec_pre.prf:
../../Qt/6.3.0/ios/mkspecs/qdevice.pri:
../../Qt/6.3.0/ios/mkspecs/features/device_config.prf:
../../Qt/6.3.0/ios/mkspecs/common/unix.conf:
../../Qt/6.3.0/ios/mkspecs/common/mac.conf:
../../Qt/6.3.0/ios/mkspecs/common/uikit.conf:
../../Qt/6.3.0/ios/mkspecs/common/ios.conf:
../../Qt/6.3.0/ios/mkspecs/common/sanitize.conf:
../../Qt/6.3.0/ios/mkspecs/common/gcc-base.conf:
../../Qt/6.3.0/ios/mkspecs/common/gcc-base-mac.conf:
../../Qt/6.3.0/ios/mkspecs/common/clang.conf:
../../Qt/6.3.0/ios/mkspecs/common/clang-mac.conf:
../../Qt/6.3.0/ios/mkspecs/common/uikit/clang.conf:
../../Qt/6.3.0/ios/mkspecs/common/uikit/qmake.conf:
../../Qt/6.3.0/ios/mkspecs/qconfig.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_freetype.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_harfbuzz.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_libjpeg.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_libpng.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_ext_pcre2.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_core.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_freetype_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_gui.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_help.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_jpeg_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsanimation.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssettings.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssettings_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssharedimage.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_linguist.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_linguist_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_network.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_png_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qml.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlcore.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmldom_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlintegration.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmllint_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quick.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicklayouts.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_sql.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svg.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svgwidgets.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_tools_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webview.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webviewquick.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_xml.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qcertonlybackend.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qgif.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qico.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qios.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qscnetworkreachability.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsecuretransportbackend.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../Qt/6.3.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
../../Qt/6.3.0/ios/mkspecs/features/qt_functions.prf:
../../Qt/6.3.0/ios/mkspecs/features/qt_config.prf:
../../Qt/6.3.0/ios/mkspecs/macx-ios-clang/qmake.conf:
../../Qt/6.3.0/ios/mkspecs/macx-xcode/qmake.conf:
../../Qt/6.3.0/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/6.3.0/ios/mkspecs/features/exclusive_builds.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/sdk.prf:
../../Qt/6.3.0/ios/mkspecs/features/uikit/sdk.prf:
../../Qt/6.3.0/ios/mkspecs/features/toolchain.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/toolchain.prf:
../../Qt/6.3.0/ios/mkspecs/features/default_pre.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/default_pre.prf:
../../Qt/6.3.0/ios/mkspecs/features/uikit/default_pre.prf:
../../Qt/6.3.0/ios/mkspecs/features/resolve_config.prf:
../../Qt/6.3.0/ios/mkspecs/features/uikit/resolve_config.prf:
../../Qt/6.3.0/ios/mkspecs/features/default_post.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/default_post.prf:
../../Qt/6.3.0/ios/mkspecs/features/uikit/default_post.prf:
../../Qt/6.3.0/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/objective_c.prf:
../../Qt/6.3.0/ios/mkspecs/features/entrypoint.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/mac.prf:
../../Qt/6.3.0/ios/mkspecs/features/uikit/bitcode.prf:
../../Qt/6.3.0/ios/mkspecs/features/warn_on.prf:
../../Qt/6.3.0/ios/mkspecs/features/qt.prf:
../../Qt/6.3.0/ios/mkspecs/features/resources_functions.prf:
../../Qt/6.3.0/ios/mkspecs/features/resources.prf:
../../Qt/6.3.0/ios/mkspecs/features/moc.prf:
../../Qt/6.3.0/ios/mkspecs/features/unix/opengl.prf:
../../Qt/6.3.0/ios/mkspecs/features/uic.prf:
../../Qt/6.3.0/ios/mkspecs/features/unix/thread.prf:
../../Qt/6.3.0/ios/mkspecs/features/qmake_use.prf:
../../Qt/6.3.0/ios/mkspecs/features/file_copies.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/rez.prf:
../../Qt/6.3.0/ios/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/6.3.0/ios/mkspecs/features/testcase_targets.prf:
../../Qt/6.3.0/ios/mkspecs/features/uikit/testcase_targets.prf:
../../Qt/6.3.0/ios/mkspecs/features/exceptions.prf:
../../Qt/6.3.0/ios/mkspecs/features/yacc.prf:
../../Qt/6.3.0/ios/mkspecs/features/lex.prf:
QtBoardGames.pro:
../../Qt/6.3.0/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard:
qml.qrc:
../../Qt/6.3.0/ios/plugins/platforms/libqios.prl:
../../Qt/6.3.0/ios/plugins/iconengines/libqsvgicon.prl:
../../Qt/6.3.0/ios/plugins/imageformats/libqgif.prl:
../../Qt/6.3.0/ios/plugins/imageformats/libqico.prl:
../../Qt/6.3.0/ios/plugins/imageformats/libqjpeg.prl:
../../Qt/6.3.0/ios/plugins/imageformats/libqsvg.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_debugger.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_inspector.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_local.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_messages.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_native.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_preview.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_profiler.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_server.prl:
../../Qt/6.3.0/ios/plugins/qmltooling/libqmldbg_tcp.prl:
../../Qt/6.3.0/ios/plugins/networkinformation/libqscnetworkreachability.prl:
../../Qt/6.3.0/ios/plugins/tls/libqsecuretransportbackend.prl:
../../Qt/6.3.0/ios/lib/libQt6Quick.prl:
../../Qt/6.3.0/ios/lib/libQt6OpenGL.prl:
../../Qt/6.3.0/ios/lib/libQt6Widgets.prl:
../../Qt/6.3.0/ios/lib/libQt6Gui.prl:
../../Qt/6.3.0/ios/lib/libQt6QmlModels.prl:
../../Qt/6.3.0/ios/lib/libQt6Qml.prl:
../../Qt/6.3.0/ios/lib/libQt6Network.prl:
../../Qt/6.3.0/ios/lib/libQt6Core.prl:
../../Qt/6.3.0/ios/qml/QtQuick/libqtquick2plugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Particles/libparticlesplugin.prl:
../../Qt/6.3.0/ios/qml/QtQml/libqmlplugin.prl:
../../Qt/6.3.0/ios/qml/QtQml/Models/libmodelsplugin.prl:
../../Qt/6.3.0/ios/qml/QtQml/WorkerScript/libworkerscriptplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Window/libquickwindowplugin.prl:
../../Qt/6.3.0/ios/qml/QtDigitalAdvertising/libDigitalAdvertising.prl:
../../Qt/6.3.0/ios/qml/QtWebView/libqtwebviewquickplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/libqtquickcontrols2plugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/impl/libqtquickcontrols2implplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Basic/libqtquickcontrols2basicstyleplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Fusion/libqtquickcontrols2fusionstyleplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Material/libqtquickcontrols2materialstyleplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Imagine/libqtquickcontrols2imaginestyleplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Universal/libqtquickcontrols2universalstyleplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Templates/libqtquicktemplates2plugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Shapes/libqmlshapesplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Basic/impl/libqtquickcontrols2basicstyleimplplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Fusion/impl/libqtquickcontrols2fusionstyleimplplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Material/impl/libqtquickcontrols2materialstyleimplplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Imagine/impl/libqtquickcontrols2imaginestyleimplplugin.prl:
../../Qt/6.3.0/ios/qml/QtQuick/Controls/Universal/impl/libqtquickcontrols2universalstyleimplplugin.prl:
../../Qt/6.3.0/ios/qml/Qt/labs/platform/libqtlabsplatformplugin.prl:
../../Qt/6.3.0/ios/qml/QtMultimedia/libquickmultimediaplugin.prl:
qmake: FORCE
	@$(QMAKE) -o QtBoardGames.xcodeproj/project.pbxproj QtBoardGames.pro -spec macx-xcode -qtconf /Users/octavian.cimpu/Qt/6.3.0/ios/bin/target_qt.conf

qmake_all: FORCE

